apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-fastapi-app
spec:
  selector:
    matchLabels:
      app: ml-fastapi
  replicas: 1
  template:
    metadata:
      labels:
        app: ml-fastapi
    spec:
      containers:
      - name: ml-fastapi-container
        image: "<AWS_ACCOUNT>.dkr.ecr.<AWS_REGION>.amazonaws.com/ml-app:<IMAGE_TAG>"
        ports:
        - containerPort: 80
