apiVersion: v1
kind: Service
metadata:
  name: ml-fastapi-service
  labels:
    app: ml-fastapi
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ml-fastapi
  type: LoadBalancer
